package com.groupSWP.centralkitchenplatform.service.store;

import com.groupSWP.centralkitchenplatform.dto.store.StoreRequest;
import com.groupSWP.centralkitchenplatform.dto.store.StoreResponse;
import com.groupSWP.centralkitchenplatform.entities.auth.Account;
import com.groupSWP.centralkitchenplatform.entities.auth.Store;
import com.groupSWP.centralkitchenplatform.entities.notification.Notification;
import com.groupSWP.centralkitchenplatform.repositories.auth.AccountRepository;
import com.groupSWP.centralkitchenplatform.repositories.store.StoreRepository;
import com.groupSWP.centralkitchenplatform.service.notification.NotificationService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors; // 🌟 Đã gom import lên đây

/**
 * Service quản lý vòng đời Cửa hàng (Store Management).
 * <p>
 * Chịu trách nhiệm tạo mới, cập nhật thông tin cửa hàng, và đặc biệt là xử lý
 * các nghiệp vụ luân chuyển nhân sự (gán quản lý, đóng cửa hàng, chuyển công tác).
 * </p>
 */
@Service
@RequiredArgsConstructor
public class StoreService {

    private final StoreRepository storeRepository;
    private final AccountRepository accountRepository;
    private final NotificationService notificationService; // 🔥 Đã tiêm NotificationService

    /**
     * Khởi tạo Cửa hàng mới.
     * <p>Tự động sinh mã Cửa hàng (Store ID) và thiết lập trạng thái mặc định là Active.</p>
     *
     * @param request Payload chứa thông tin cửa hàng mới.
     * @return DTO chứa thông tin Cửa hàng vừa tạo.
     */
    @Transactional
    public StoreResponse createStore(StoreRequest request) {

        // 1. Tự động sinh ID (Ví dụ: ST-A1B2C3)
        // Cách này lấy 8 ký tự đầu của UUID viết hoa
        String autoGeneratedId = "ST-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();

        // 2. Map từ Request sang Entity
        Store store = new Store();
        store.setStoreId(autoGeneratedId); // Gán ID vừa sinh
        store.setName(request.getName());
        store.setAddress(request.getAddress());
        store.setPhone(request.getPhone());
        store.setType(request.getType());
        store.setActive(true); // Mặc định là Active

        // 3. Lưu xuống Database
        Store savedStore = storeRepository.save(store);

        // 4. Convert Entity sang Response DTO để trả về
        return mapToResponse(savedStore);
    }

    /**
     * Cập nhật thông tin chi tiết Cửa hàng.
     *
     * @param storeId Mã định danh Cửa hàng cần sửa.
     * @param request Payload chứa các thông tin thay đổi.
     * @return DTO chứa thông tin Cửa hàng sau cập nhật.
     */
    @Transactional
    public StoreResponse updateStore(String storeId, StoreRequest request) {

        Store existingStore = storeRepository.findById(storeId)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy cửa hàng với ID: " + storeId));

        if (request.getName() != null && !request.getName().isEmpty()) {
            existingStore.setName(request.getName());
        }

        if (request.getAddress() != null && !request.getAddress().isEmpty()) {
            existingStore.setAddress(request.getAddress());
        }

        if (request.getPhone() != null && !request.getPhone().isEmpty()) {
            existingStore.setPhone(request.getPhone());
        }

        if (request.getType() != null && !request.getType().isEmpty()) {
            existingStore.setType(request.getType());
        }

        Store savedStore = storeRepository.save(existingStore);
        return mapToResponse(savedStore);
    }

    // ======================================================
    // LẤY DANH SÁCH TẤT CẢ CỬA HÀNG (API: /all)
    // ======================================================
    public List<StoreResponse> getAllStores() { // 🌟 Đã tối ưu FQN
        return storeRepository.findAll().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList()); // 🌟 Đã tối ưu FQN
    }

    public List<StoreResponse> getEmptyStores() {
        return storeRepository.findEmptyStores().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList()); // 🌟 Đã tối ưu FQN
    }

    // ======================================================
    // 🌟 NGHIỆP VỤ 1: THAY ĐỔI / GÁN QUẢN LÝ CỬA HÀNG
    // ======================================================
    /**
     * Bổ nhiệm Quản lý cho Cửa hàng.
     * <p>Xử lý việc tháo quyền quản lý của người cũ (nếu có) trước khi bổ nhiệm người mới.</p>
     *
     * @param storeId   Mã Cửa hàng.
     * @param accountId Mã Tài khoản nhân sự được bổ nhiệm.
     * @return Thông báo kết quả bổ nhiệm.
     */
    @Transactional
    public String changeStoreManager(String storeId, UUID accountId) {
        Store store = storeRepository.findById(storeId)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy cửa hàng!"));

        Account newManager = accountRepository.findById(accountId)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy tài khoản nhân sự!"));

        if (!newManager.isActive()) {
            throw new RuntimeException("Tài khoản này đang bị khóa (Inactive), không thể gán làm quản lý!");
        }

        // 🌟 Kiểm tra xem người mới có đang trống việc không
        if (newManager.getStore() != null) {
            throw new RuntimeException("Tài khoản này hiện đang quản lý cửa hàng '" + newManager.getStore().getName() + "'. Vui lòng chọn nhân sự đang TRỐNG VIỆC!");
        }

        // 🛠️ BƯỚC FIX LỖI: Tháo "ghế" quản lý của người cũ ra trước (Nếu tiệm đang có người)
        Account oldManager = store.getAccount();
        if (oldManager != null) {
            oldManager.setStore(null); // Tước quyền
            accountRepository.saveAndFlush(oldManager); // 🔥 Bắt buộc dùng saveAndFlush để DB lập tức nhả cái cờ Unique ra!
        }

        // Sau khi ghế đã trống, gán cho người mới
        newManager.setStore(store);
        accountRepository.save(newManager);

        // 🔥 THÔNG BÁO 1: Báo cho Quản lý mới biết đã được cấp tiệm
        notificationService.sendNotification(
                newManager,
                "🎉 BỔ NHIỆM QUẢN LÝ",
                "Chúc mừng! Bạn đã được bổ nhiệm làm Quản lý của cửa hàng: " + store.getName(),
                Notification.NotificationType.INFO,
                null
        );

        return "Đã gán tài khoản " + newManager.getUsername() + " làm Quản lý cửa hàng: " + store.getName();
    }

    // ======================================================
    // 🌟 NGHIỆP VỤ 2: XÓA MỀM CỬA HÀNG
    // ======================================================
    /**
     * Xóa mềm (Vô hiệu hóa) Cửa hàng và xử lý luân chuyển nhân sự.
     * <p>Đảm bảo Cửa hàng trưởng cũ không bị "mất việc" bằng cách ép luân chuyển sang tiệm mới.</p>
     *
     * @param storeId           Mã Cửa hàng cần đóng.
     * @param transferToStoreId Mã Cửa hàng đích để luân chuyển Quản lý cũ sang.
     * @return Thông báo kết quả đóng cửa và luân chuyển.
     */
    @Transactional
    public String softDeleteStore(String storeId, String transferToStoreId) {
        Store store = storeRepository.findById(storeId)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy cửa hàng!"));

        if (!store.isActive()) {
            throw new RuntimeException("Cửa hàng này đã được đóng cửa từ trước rồi!");
        }

        Account currentManager = store.getAccount();
        Store targetStore = null; // 🌟 Khai báo ở đây để lát xài trong câu thông báo

        // NẾU CỬA HÀNG ĐANG CÓ NHÂN VIÊN VÀ ĐANG ACTIVE
        if (currentManager != null && currentManager.isActive()) {

            if (transferToStoreId == null || transferToStoreId.trim().isEmpty()) {
                throw new RuntimeException("Cửa hàng đang có nhân viên quản lý! Vui lòng chọn một Cửa hàng TRỐNG để đẩy nhân viên này qua.");
            }
            if (storeId.equals(transferToStoreId)) {
                throw new RuntimeException("Không thể luân chuyển sang chính cửa hàng đang muốn đóng!");
            }

            targetStore = storeRepository.findById(transferToStoreId)
                    .orElseThrow(() -> new RuntimeException("Cửa hàng đích để luân chuyển không tồn tại!"));

            if (!targetStore.isActive()) {
                throw new RuntimeException("Cửa hàng đích đang bị Đóng cửa (Inactive), không thể đẩy nhân viên tới!");
            }
            if (targetStore.getAccount() != null) {
                throw new RuntimeException("Cửa hàng đích ĐÃ CÓ người quản lý rồi! Vui lòng chọn một cửa hàng đang TRỐNG!");
            }

            // 🛠️ LUÂN CHUYỂN CHUẨN SÁCH GIÁO KHOA JPA:
            // 1. Phải tháo chức của người cũ ở tiệm này (Để Java hiểu là 2 đứa đã ly hôn)
            store.setAccount(null);

            // 2. Cấp hộ khẩu cho người đó sang tiệm mới
            currentManager.setStore(targetStore);
            targetStore.setAccount(currentManager);

            // (Không cần gọi accountRepository.save() ở đây vì @Transactional sẽ tự động lo)
        }

        // ĐÓNG CỬA HÀNG (INACTIVE)
        store.setActive(false);

        // Chỉ gọi save đúng 1 lần duy nhất cho toàn bộ quá trình!
        storeRepository.save(store);

        // 🔥 THÔNG BÁO 2: Báo cho Quản lý cũ biết tiệm đã đóng / luân chuyển
        if (currentManager != null) {
            String msg = targetStore != null ?
                    "Cửa hàng cũ đã đóng. Bạn được điều chuyển sang quản lý cửa hàng: " + targetStore.getName() :
                    "Cửa hàng của bạn đã bị đóng. Hiện tại bạn đang ở trạng thái dự bị.";

            notificationService.sendNotification(
                    currentManager,
                    "🔄 LUÂN CHUYỂN CÔNG TÁC",
                    msg,
                    Notification.NotificationType.WARNING,
                    null
            );
        }

        // 🌟 Trả về thông báo siêu chi tiết
        return (currentManager != null && targetStore != null) ?
                "Đã ĐÓNG CỬA tiệm [" + store.getName() + "] (ID: " + store.getStoreId() + "). " +
                        "Nhân sự [" + currentManager.getUsername() + "] đã được luân chuyển an toàn sang tiệm mới [" + targetStore.getName() + "] (ID: " + targetStore.getStoreId() + ")!" :
                "Đã ĐÓNG CỬA tiệm [" + store.getName() + "] (ID: " + store.getStoreId() + ") thành công!";
    }

//    @Transactional
//    public void deleteStore(String storeId) {
//        Store store = storeRepository.findById(storeId)
//                .orElseThrow(() -> new RuntimeException("Không tìm thấy cửa hàng!"));
//
//        if (store.getOrders() != null && !store.getOrders().isEmpty()) {
//            throw new RuntimeException("Không thể xóa cửa hàng này vì đã có phát sinh đơn hàng! Hãy dùng chức năng 'Khóa' (Soft Delete) thay vì xóa.");
//        }
//        storeRepository.delete(store);
//    }

    private StoreResponse mapToResponse(Store store) {
        return StoreResponse.builder()
                .storeId(store.getStoreId())
                .name(store.getName())
                .address(store.getAddress())
                .phone(store.getPhone())
                .type(store.getType())
                .isActive(store.isActive())
                .build();
    }
}