package com.groupSWP.centralkitchenplatform.service;

import com.groupSWP.centralkitchenplatform.dto.store.StoreRequest;
import com.groupSWP.centralkitchenplatform.dto.store.StoreResponse;
import com.groupSWP.centralkitchenplatform.entities.auth.Store;
import com.groupSWP.centralkitchenplatform.repositories.StoreRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class StoreService {

    private final StoreRepository storeRepository;

    @Transactional
    public StoreResponse createStore(StoreRequest request) {

        // 1. Tự động sinh ID (Ví dụ: ST-A1B2C3)
        // Cách này lấy 8 ký tự đầu của UUID viết hoa
        String autoGeneratedId = "ST-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();

        // 2. Map từ Request sang Entity
        Store store = new Store();
        store.setStoreId(autoGeneratedId); // Gán ID vừa sinh
        store.setName(request.getName());
        store.setAddress(request.getAddress());
        store.setPhone(request.getPhone());
        store.setType(request.getType());
        store.setActive(true); // Mặc định là Active

        // 3. Lưu xuống Database
        Store savedStore = storeRepository.save(store);

        // 4. Convert Entity sang Response DTO để trả về
        return mapToResponse(savedStore);
    }


    @Transactional
    public StoreResponse updateStore(String storeId, StoreRequest request) {
        // 1. Tìm Store bằng ID truyền vào từ URL
        Store existingStore = storeRepository.findById(storeId)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy cửa hàng với ID: " + storeId));

        // 2. LOGIC CẬP NHẬT (Giữ nguyên logic kiểm tra null)
        // Lưu ý: Không quan tâm ID trong request (nếu có), chỉ tin tưởng storeId từ tham số

        if (request.getName() != null && !request.getName().isEmpty()) {
            existingStore.setName(request.getName());
        }

        if (request.getAddress() != null && !request.getAddress().isEmpty()) {
            existingStore.setAddress(request.getAddress());
        }

        if (request.getPhone() != null && !request.getPhone().isEmpty()) {
            existingStore.setPhone(request.getPhone());
        }

        if (request.getType() != null && !request.getType().isEmpty()) {
            existingStore.setType(request.getType());
        }

        // 3. Lưu và trả về
        Store savedStore = storeRepository.save(existingStore);
        return mapToResponse(savedStore);
    }

    // --- HÀM HELPER: Chuyển Entity sang DTO (Dùng chung) ---
    private StoreResponse mapToResponse(Store store) {
        return StoreResponse.builder()
                .storeId(store.getStoreId())
                .name(store.getName())
                .address(store.getAddress())
                .phone(store.getPhone())
                .type(store.getType())
                .isActive(store.isActive())
                .build();
    }
}