spring.application.name=E-CommercePlatform
# 1. URL k?t n?i (Thay centralkitchen_db b?ng tên schema b?n t?o trong MySQL Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/centralkitchen_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# 2. Tài kho?n MySQL
server.port=8081
spring.datasource.username=root
spring.datasource.password=12345

# 3. Driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. C?u hình Hibernate cho MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# S? d?ng Dialect cho MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# cau hinh gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=datntse180352@fpt.edu.vn
spring.mail.password=afhi audu puuu otrc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# =======================================================
# JWT SECURITY CONFIGURATION
# =======================================================
# Khóa bí m?t (Chu?i Hex ng?u nhiên 256-bit c?c k? b?o m?t)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Th?i gian s?ng c?a Token: 86400000 ms (T??ng ???ng 24 gi?)
jwt.expiration=86400000


# ==========================================
# VNPAY SANDBOX CONFIGURATION
# ==========================================
vnpay.tmnCode=NMOUJT1T
vnpay.hashSecret=SRR1QI9A4844VCZ2Y212GPSTFF8K38B7
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8081/api/payment/vnpay-return